// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWSD0kyLq7Lb5qy-D5V7-clbsDrGhLNpw',
    appId: '1:350847407157:web:46d48bfe6957ea61038d7c',
    messagingSenderId: '350847407157',
    projectId: 'mitjul-270ec',
    authDomain: 'mitjul-270ec.firebaseapp.com',
    storageBucket: 'mitjul-270ec.firebasestorage.app',
    measurementId: 'G-EG5V327YBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg7J1bp0dCytXP_OjJKrAoxsML2_6MlrI',
    appId: '1:350847407157:android:5ee1caa4128a2b95038d7c',
    messagingSenderId: '350847407157',
    projectId: 'mitjul-270ec',
    storageBucket: 'mitjul-270ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACXNa2TA4VWOlwLSROO1N4JeGLefC6Gyg',
    appId: '1:350847407157:ios:cb2d498e671044a8038d7c',
    messagingSenderId: '350847407157',
    projectId: 'mitjul-270ec',
    storageBucket: 'mitjul-270ec.firebasestorage.app',
    iosClientId: '350847407157-cvve8i18rk6g8en1pbu04h7egeeh45gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mitjulAppNew',
  );

}